# Generated by Django 4.0 on 2022-05-26 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Machine_api', '0003_alter_organisation_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='projects',
            field=models.ManyToManyField(blank=True, to='Machine_api.Project'),
        ),
    ]
