# Generated by Django 4.0 on 2022-06-14 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Machine_api', '0004_alter_organisation_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='LPTN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.JSONField(blank=True, default=list, null=True)),
                ('result', models.JSONField(blank=True, default=list, null=True)),
                ('machine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Machine_api.machine')),
            ],
        ),
    ]
