# Generated by Django 4.0 on 2022-06-16 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Machine_api', '0005_lptn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lptn',
            name='machine',
        ),
        migrations.AddField(
            model_name='machine',
            name='lptn',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Machine_api.lptn'),
        ),
    ]
