# Generated by Django 4.0 on 2022-07-05 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Machine_api', '0006_remove_lptn_machine_machine_lptn'),
    ]

    operations = [
        migrations.CreateModel(
            name='Winding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('data', models.JSONField(blank=True, default=list, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='rotor',
            name='winding',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Machine_api.winding'),
        ),
        migrations.AddField(
            model_name='stator',
            name='winding',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Machine_api.winding'),
        ),
    ]
